# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98fa2fd18ef2d4fc98956640174a2b8924837e2f77f3a512ed1e83fc3b6321a2491e5e186ef10d65f2523ab11567d9511b7818be432a55b6f155494ee9818228

test:
  secret_key_base: 3e649c2ba6ca3f5b5dc156cb1da215d681a1db9891aa04aa546ec086079c59d4a484c5ebde3d7871b5450bbec11be3ffeae4e08118febb67791bcf6bcf42dccb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
